my_demo_folder_path: "home/ec2-user/my_new_folder"
public_ip: "54.77.222.175"
server_name: "{{ public_ip }}"
document_root: "/var/www/html"
app_root: "html_demo_site-main"

handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted 
